# Generated by Django 6.0.4 on 2026-06-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('restaurants', '0001_initial'), ('restaurants', '0002_add_menuitem_fields'), ('restaurants', '0003_menuitem_day_alter_menuitem_parent'), ('restaurants', '0004_rename_extra_menuitem_extra_menu_and_more'), ('restaurants', '0005_remove_menuitem_url_menuitem_storage_url'), ('restaurants', '0006_rename_pork_menuitem_non_pork_alter_menuitem_price'), ('restaurants', '0007_alter_menuitem_day_alter_menuitem_extra_menu_and_more'), ('restaurants', '0008_alter_menuitem_options_and_more'), ('restaurants', '0009_menuitem_enmain_menuitem_enside'), ('restaurants', '0010_menuitem_enmain')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('main', models.CharField(max_length=200)),
                ('side', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('stamp', models.BooleanField(default=False)),
                ('day', models.CharField(blank=True, max_length=200, null=True)),
                ('extra', models.CharField(blank=True, max_length=200, null=True)),
                ('meal', models.CharField(blank=True, max_length=200, null=True)),
                ('enextra', models.CharField(blank=True, max_length=200, null=True)),
                ('enside', models.CharField(blank=True, max_length=200, null=True)),
                ('enmain', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['place'],
            },
        ),
    ]
