# Generated by Django 6.0.4 on 2026-06-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('main', models.CharField(max_length=200)),
                ('side', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('stamp', models.BooleanField(default=False)),
                ('day', models.CharField(blank=True, max_length=200, null=True)),
                ('extra', models.CharField(blank=True, max_length=200, null=True)),
                ('meal', models.CharField(blank=True, max_length=200, null=True)),
                ('enextra', models.CharField(blank=True, max_length=200, null=True)),
                ('enside', models.CharField(blank=True, max_length=200, null=True)),
                ('enmain', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['place'],
            },
        ),
    ]
