# Generated by Django 6.0.4 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='main',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='side',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='time',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='place',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='extra',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='pork',
            field=models.BooleanField(default=False),
        ),
    ]
