# Generated by Django 6.0.4 on 2026-05-25 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_add_menuitem_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='day',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='restaurants.menuitem'),
        ),
    ]
