# Generated by Django 6.0.4 on 2026-05-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_menuitem_day_alter_menuitem_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='extra',
            new_name='extra_menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='extra_price',
            field=models.IntegerField(default=0),
        ),
    ]
