# Generated by Django 6.0.4 on 2026-05-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_extra_menuitem_extra_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='storage_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
