# Generated by Django 6.0.4 on 2026-05-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_menuitem_url_menuitem_storage_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='pork',
            new_name='non_pork',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
