# Generated by Django 6.0.4 on 2026-05-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_rename_pork_menuitem_non_pork_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='extra_menu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='extra_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='storage_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
