# Generated by Django 6.0.4 on 2026-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_menuitem_day_alter_menuitem_extra_menu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['place']},
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='extra_menu',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='storage_url',
            new_name='extra',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='non_pork',
            new_name='stamp',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='time',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='title',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='meal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
