# Generated by Django 6.0.4 on 2026-06-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='enmain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='enside',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
