# Generated by Django 6.0.4 on 2026-06-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_menuitem_enmain_menuitem_enside'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='enmain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
