# Generated by Django 6.0.4 on 2026-06-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_menuitem_enmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='enextra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
