services:
  web:
    build: .
    container_name: food
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
