MEALS = [{'id': 0, 'name': '아침', 'time': 'breakfast'}, {'id': 1, 'name': '점심', 'time': 'lunch'}, {'id': 2, 'name': '간식', 'time': 'snack'}, {'id': 3, 'name': '저녁', 'time': 'dinner'}, {'id': 4, 'name': 'One-Dish', 'time': 'onedish'}, {'id': 5, 'name': '무인판매', 'time': 'unmanned'}]
WEEKDAYS = [{'id': 0, 'name': '월', 'day': 'mon'}, {'id': 1, 'name': '화', 'day': 'tue'}, {'id': 2, 'name': '수', 'day': 'wed'}, {'id': 3, 'name': '목', 'day': 'thu'}, {'id': 4, 'name': '금', 'day': 'fri'}]
RESTAURANTS = [
    {'id': 1, 'title': '청운관 학생식당', 'campus': 'se', 'path': 'ch', 'icon': 'utensils-crossed', 'color': '#2563eb', 'mealsSemester': ['아침', '점심', '간식', '저녁'], 'mealsSemesterTime': ['08:30~10:00 (간편식: 09:00~10:00)', '11:00~14:30', '15:00~16:00', '17:00~18:30'], 'mealsVacation': ['아침', '점심', '간식'], 'mealsVacationTime': ['(간편식: 09:00~10:00)', '11:00~14:00', '14:30~15:30']},
    {'id': 2, 'title': '청운관 교직원식당', 'campus': 'se', 'path': 'cg', 'icon': 'chef-hat', 'color': '#059669', 'mealsSemester': ['점심'], 'mealsVacation': ['점심'], 'mealsSemesterTime': ['11:00~14:00'], 'mealsVacationTime': ['11:00~13:30']},
    {'id': 3, 'title': '푸른솔 학생식당', 'campus': 'se', 'path': 'ph', 'icon': 'utensils', 'color': '#d97706', 'mealsSemester': ['아침', '점심', 'One-Dish', '무인판매'], 'mealsVacation': ['아침', '점심', 'One-Dish', '무인판매'], 'mealsSemesterTime': ['08:30~10:00 (간편식: 09:00~10:00)', '11:00~14:30', '08:30~16:00', '14:30~소진시까지'], 'mealsVacationTime': ['09:00~09:50', '11:00~14:00', '08:30~16:00', '14:00~소진시까지']},
    {'id': 4, 'title': '푸른솔 교직원식당', 'campus': 'se', 'path': 'pg', 'icon': 'cooking-pot', 'color': '#dc2626', 'mealsSemester': ['점심'], 'mealsVacation': ['점심'], 'mealsSemesterTime': ['11:00~14:00'], 'mealsVacationTime': ['11:00~13:30']},
    {'id': 5, 'title': '한국외대 인문관 식당', 'campus': 'se', 'path': 'his', 'icon': 'building-2', 'color': '#7c3aed', 'mealsSemester': ['아침', '점심', '저녁'], 'mealsVacation': ['점심', '저녁'], 'mealsSemesterTime': ['08:00~10:00', '11:00~14:30', '16:40~18:40'], 'mealsVacationTime': ['11:00~14:00', '16:40~18:40']},
    {'id': 6, 'title': '한국외대 교수회관 식당', 'campus': 'se', 'path': 'hgs', 'icon': 'landmark', 'color': '#0891b2', 'mealsSemester': ['점심'], 'mealsVacation': ['점심'], 'mealsSemesterTime': ['11:00~13:30'], 'mealsVacationTime': ['11:00~13:30']},
    {'id': 7, 'title': '학생회관 학생식당', 'campus': 'gl', 'path': 'hh', 'icon': 'school', 'color': '#db2777', 'mealsSemester': ['아침', '점심', '저녁'], 'mealsVacation': ['점심'], 'mealsSemesterTime': ['08:20~10:00', '11:00~14:00', '17:00~18:30'], 'mealsVacationTime': ['11:30~13:30']},
    {'id': 8, 'title': '학생회관 교직원식당', 'campus': 'gl', 'path': 'hg', 'icon': 'book-open', 'color': '#ca8a04', 'mealsSemester': ['점심', '저녁'], 'mealsVacation': ['점심'], 'mealsSemesterTime': ['11:00~14:00', '17:00~18:30'], 'mealsVacationTime': ['11:30~13:30']},
    {'id': 9, 'title': '제2기숙사 식당', 'campus': 'gl', 'path': 'jg', 'icon': 'home', 'color': '#65a30d', 'mealsSemester': ['아침', '점심', '저녁'], 'mealsVacation': ['아침', '점심', '저녁'], 'mealsSemesterTime': ['08:00~09:00', '11:30~13:30', '17:30~19:00'], 'mealsVacationTime': ['08:00~09:00', '11:30~13:30', '17:30~19:00']},
]
LOCATIONS = {
    'ch': '청운관 학생식당',
    'cg': '청운관 교직원식당',
    'ph': '푸른솔 학생식당',
    'pg': '푸른솔 교직원식당',
    'his': '한국외대 인문관 식당',
    'hgs': '한국외대 교수회관 식당',
    'hh': '학생회관 학생식당',
    'hg': '학생회관 교직원식당',
    'jg': '제2기숙사 식당',
}
FIXED_MENU = {
    'ch' : [
        {
            'id': '만두라면,치즈라면-ch',
            'main': '만두라면, 치즈라면', 
            'enmain': 'Dumpling Ramen, Cheese Ramen',
            'side': None, 
            'enside': None,
            'price': 3000, 
            'day': None, 
            'time_category': ['breakfast', 'snack'], 
            'time_detail': {'breakfast': ['09:00', '10:00'], 'snack': ['15:00', '16:00']}, 
            'place': 'ch', 
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
        {
            "id": "속풀이라면-ch",
            "main": "속풀이라면",
            "enmain": "Sokpul Ramen",
            "side": None,
            "enside": None,
            "price": 3500,
            "day": None,
            "time_category": ["breakfast"],
            "time_detail": {"breakfast": ["09:00", "10:00"]},
            "place": "ch",
            "extra": None,
            "enextra": None,
            "stamp": False,
        },
        {
            "id": '공깃밥-ch',
            "main": "공깃밥",
            "enmain": "Rice",
            "side": None,
            "enside": None,
            "price": 800,
            "day": None,
            "time_category": ["breakfast", "snack"],
            "time_detail": {"breakfast": ["09:00", "10:00"], "snack": ["15:00", "16:00"]},
            "place": "ch", 
            "extra": None,
            "enextra": None,
            "stamp": False,
        },
        {
            'id': '짜계치-ch',
            "main": "짜계치",
            "enmain": "Jja-gye-chi",
            "side": None,
            "enside": None,
            "price": 3800,
            "day": None,
            "time_category": ["snack"],
            "time_detail": {"snack": ["15:00", "16:00"]},
            "place": "ch",
            "extra": None,
            "enextra": None,
            "stamp": False,
        },
        {
            'id': '콘치즈불닭면-ch',
            "main": "콘치즈불닭면",
            "enmain": "Corn Cheese Buldak Noodles",
            "side": None,
            "enside": None,
            "price": 3800,
            "day": None,
            "time_category": ["snack"],
            "time_detail": {"snack": ["15:00", "16:00"]},
            "place": "ch",
            "extra": None,
            "enextra": None,
            "stamp": False,
        },
        {
            'id': '음료(콜라,사이다)-ch',
            "main": "음료(콜라,사이다)",
            "enmain": "Soft Drink (Cola, Cider)",
            "side": None,
            "enside": None,
            "price": 1700,
            "day": None,
            "time_category": ["breakfast"],
            "time_detail": {"breakfast": ["09:00", "10:00"]},
            "place": "ch",
            "extra": None,
            "enextra": None,
            "stamp": False,
        },
        {
            'id': '컵씨리얼&우유-ch',
            "main": "컵씨리얼&우유",
            "enmain": "Cup Cereal & Milk",
            "side": None,
            "enside": None,
            "price": 2000,
            "day": None,
            "time_category": ["breakfast"],
            "time_detail": {"breakfast": ["09:00", "10:00"]},
            "place": "ch",
            "extra": None,
            "enextra": None,
            "stamp": False,
        },
        {
            'id': '우유_딸기우유_초코우유-ch',
            "main": "우유/딸기우유/초코우유",
            "enmain": "Milk / Strawberry Milk / Choco Milk",
            "side": None,
            "enside": None,
            "price": 900,
            "day": None,
            "time_category": ["breakfast"],
            "time_detail": {"breakfast": ["09:00", "10:00"]},
            "place": "ch",
            "extra": None,
            "enextra": None,
            "stamp": False,
        },
    ],
    'ph' : [
        {
            'id': '주먹밥1EA-ph',
            'main': '주먹밥1EA',
            'enmain': 'Rice Ball 1EA',
            'side': None,
            'enside': None,
            'price': 1300,
            'day': None,
            'time_category': ['onedish'],
            'time_detail': {'onedish': ['08:30', '16:00']},
            'place': 'ph',
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
        {
            'id': '주먹밥2EA-ph',
            'main': '주먹밥2EA',
            'enmain': 'Rice Ball 2EA',
            'side': None,
            'enside': None,
            'price': 2500,
            'day': None,
            'time_category': ['onedish', 'unmanned'],
            'time_detail': {'onedish': ['08:30', '16:00'], 'unmanned': ['16:30', '소진시까지']},
            'place': 'ph',
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
        {
            'id': '공깃밥-ph',
            'main': '공깃밥',
            'enmain': 'Rice',
            'side': None,
            'enside': None,
            'price': 800,
            'day': None,
            'time_category': ['onedish'],
            'time_detail': {'onedish': ['08:30', '16:00']},
            'place': 'ph',
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
        {
            'id': '컵씨리얼&우유-ph',
            'main': '컵씨리얼&우유',
            'enmain': 'Cup Cereal & Milk',
            'side': None,
            'enside': None,
            'price': 2000,
            'day': None,
            'time_category': ['onedish'],
            'time_detail': {'onedish': ['08:30', '16:00']},
            'place': 'ph',
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
        {
            'id': '우유_딸기우유_초코우유-ph',
            "main": "우유/딸기우유/초코우유",
            "enmain": "Milk / Strawberry Milk / Choco Milk",
            'side': None,
            'enside': None,
            'price': 900,
            'day': None,
            'time_category': ['onedish'],
            'time_detail': {'onedish': ['08:30', '16:00']},
            'place': 'ph',
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
        {
            'id': '음료(콜라,사이다)-ph',
            'main': '음료(콜라,사이다)',
            'enmain': 'Soft Drink (Cola, Cider)',
            'side': None,
            'enside': None,
            'price': 1700,
            'day': None,
            'time_category': ['onedish'],
            'time_detail': {'onedish': ['08:30', '16:00']},
            'place': 'ph',
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
        {
            'id': '진라면매운_안성탕면(셀프조리)-ph',
            'main': '진라면매운/안성탕면(셀프조리)',
            'enmain': 'Jin Ramen Spicy / Ansung Tangmyun (Self-cook)',
            'side': '김치/무맛김치/단무지/깍두기',
            'enside': 'Kimchi / Mild Kimchi / Pickled Radish / Cubed Radish Kimchi',
            'price': 2000,
            'day': None,
            'time_category': ['onedish'],
            'time_detail': {'onedish': ['08:30', '16:00']},
            'place': 'ph',
            'extra': '토핑 대파쏭쏭 500 왕계란 500',
            'enextra': 'Topping Green Onion 500 King Egg 500',
            'stamp': False,
        },
        {
            'id': '신라면(셀프조리)-ph',
            'main': '신라면(셀프조리)',
            'enmain': 'Shin Ramen (Self-cook)',
            'side': '김치/무맛김치/단무지/깍두기',
            'enside': 'Kimchi / Mild Kimchi / Pickled Radish / Cubed Radish Kimchi',
            'price': 2200,
            'day': None,
            'time_category': ['onedish'],
            'time_detail': {'onedish': ['08:30', '16:00']},
            'place': 'ph',
            'extra': '토핑 대파쏭쏭 500 왕계란 500',
            'enextra': 'Topping Green Onion 500 King Egg 500',
            'stamp': False,
        },
        {
            'id': '너구리_짜파게티(셀프조리)-ph',
            'main': '너구리/짜파게티(셀프조리)',
            'enmain': 'Neoguri / Jjapaghetti (Self-cook)',
            'side': '김치/무맛김치/단무지/깍두기',
            'enside': 'Kimchi / Mild Kimchi / Pickled Radish / Cubed Radish Kimchi',
            'price': 2300,
            'day': None,
            'time_category': ['onedish'],
            'time_detail': {'onedish': ['08:30', '16:00']},
            'place': 'ph',
            'extra': '토핑 대파쏭쏭 500 왕계란 500',
            'enextra': 'Topping Green Onion 500 King Egg 500',
            'stamp': False,
        },
        {
            'id': '오늘의컵밥-ph',
            'main': '오늘의컵밥',
            'enmain': "Today's Cup Rice",
            'side': None,
            'enside': None,
            'price': '2800~5000',
            'day': None,
            'time_category': ['unmanned'],
            'time_detail': {'unmanned': ['16:30', '소진시까지']},
            'place': 'ph',
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
        {
            'id': '김밥-ph',
            'main': '김밥',
            'enmain': 'Gimbap',
            'side': None,
            'enside': None,
            'price': '3000~4000',
            'day': ['mon', 'tue', 'wed', 'thu'],
            'time_category': ['unmanned'],
            'time_detail': {'unmanned': ['16:30', '소진시까지']},
            'place': 'ph',
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
        {
            'id': '소고기유부초밥-ph',
            'main': '소고기유부초밥',
            'enmain': 'Beef Inari Sushi',
            'side': None,
            'enside': None,
            'price': 2700,
            'day': ['mon', 'tue', 'wed', 'thu'],
            'time_category': ['unmanned'],
            'time_detail': {'unmanned': ['16:30', '소진시까지']},
            'place': 'ph',
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
    ],
    'jg' : [
        {
            'id': '오늘의샐러드&드레싱-jg',
            'main': '오늘의샐러드&드레싱',
            'enmain': "Today's Salad & Dressing",
            'side': None,
            'enside': None,
            'price': 6500,
            'day': None,
            'time_category': ['breakfast'],
            'time_detail': {'breakfast': ['08:00', '10:00']},
            'place': 'jg',
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
        {
            'id': '신라면_진라면매운맛_진라면순한맛_너구리_짜파게티_안성탕면_오징어짬뽕(셀프&토핑2종)-jg',
            'main': '신라면/진라면매운맛/진라면순한맛/너구리/짜파게티/안성탕면/오징어짬뽕(셀프&토핑2종)',
            'enmain': 'Shin Ramen / Jin Ramen Spicy / Jin Ramen Mild / Neoguri / Jjapaghetti / Ansung Tangmyun / Squid Jjambbong (Self & 2 Toppings)',
            'side': None,
            'enside': None,
            'price': 3000,
            'day': None,
            'time_category': ['breakfast', 'lunch', 'dinner'],
            'time_detail': {'breakfast': ['08:00', '10:00'], 'lunch': ['11:00', '14:00'], 'dinner': ['17:00', '18:30']},
            'place': 'jg',
            'extra': None,
            'enextra': None,
            'stamp': False,
        },
    ]
}
