MEALS = [{'id': 0, 'name': '아침', 'time': 'breakfast'}, {'id': 1, 'name': '점심', 'time': 'lunch'}, {'id': 2, 'name': '간식', 'time': 'snack'}, {'id': 3, 'name': '저녁', 'time': 'dinner'}]
WEEKDAYS = [{'id': 0, 'name': '월', 'day': 'mon'}, {'id': 1, 'name': '화', 'day': 'tue'}, {'id': 2, 'name': '수', 'day': 'wed'}, {'id': 3, 'name': '목', 'day': 'thu'}, {'id': 4, 'name': '금', 'day': 'fri'}]
RESTAURANTS = [
    {'id': 1, 'title': '청운관 학생식당', 'campus': 'se', 'path': 'ch', 'mealsSemester': ['아침', '점심', '간식', '저녁'], 'mealsSemesterTime': ['08:30~10:00 (간편식: 09:00~10:00)', '11:00~14:30', '15:00~16:00', '17:00~18:30'], 'mealsVacation': ['점심']},
    {'id': 2, 'title': '청운관 교직원식당', 'campus': 'se', 'path': 'cg', 'mealsSemester': ['점심'], 'mealsVacation': ['점심'], 'mealsSemesterTime': ['11:30~14:00']},
    {'id': 3, 'title': '푸른솔 학생식당', 'campus': 'se', 'path': 'ph', 'mealsSemester': ['아침', '점심'], 'mealsVacation': ['아침', '점심'], 'mealsSemesterTime': ['08:30~10:00 (간편식: 09:00~10:00)', '11:00~14:30']},
    {'id': 4, 'title': '푸른솔 교직원식당', 'campus': 'se', 'path': 'pg', 'mealsSemester': ['점심'], 'mealsVacation': ['점심'], 'mealsSemesterTime': ['11:30~14:00']},
    {'id': 5, 'title': '한국외대 인문관 식당', 'campus': 'se', 'path': 'hi', 'mealsSemester': ['아침', '점심', '저녁'], 'mealsVacation': ['아침', '점심', '저녁'], 'mealsSemesterTime': ['08:30~10:00 (간편식: 09:00~10:00)', '11:00~14:30', '17:00~18:30']},
    {'id': 6, 'title': '한국외대 교수회관 식당', 'campus': 'se', 'path': 'hg', 'mealsSemester': ['점심'], 'mealsVacation': ['점심'], 'mealsSemesterTime': ['11:30~14:00']},
    {'id': 7, 'title': '학생회관 학생식당', 'campus': 'gl', 'path': 'hh', 'mealsSemester': ['아침', '점심', '저녁'], 'mealsVacation': ['아침', '점심', '저녁'], 'mealsSemesterTime': ['08:30~10:00 (간편식: 09:00~10:00)', '11:00~14:30', '17:00~18:30']},
    {'id': 8, 'title': '학생회관 교직원식당', 'campus': 'gl', 'path': 'hg', 'mealsSemester': ['점심'], 'mealsVacation': ['점심'], 'mealsSemesterTime': ['11:30~14:00']},
    {'id': 9, 'title': '제2기숙사 식당', 'campus': 'gl', 'path': 'jg', 'mealsSemester': ['아침', '점심', '저녁'], 'mealsVacation': ['아침', '점심', '저녁'], 'mealsSemesterTime': ['08:30~10:00 (간편식: 09:00~10:00)', '11:00~14:30', '17:00~18:30']},
]
FIXED_MENU = {
 'ch' : [
    {
        'id': '만두라면,치즈라면-ch',
        'main': '만두라면, 치즈라면', 
        'enmain': 'Dumpling Ramen, Cheese Ramen',
        'side': None, 
        'enside': None,
        'price': 3000, 
        'day': None, 
        'time_category': ['breakfast', 'snack'], 
        'time_detail': {'breakfast': ['09:00', '10:00'], 'snack': ['15:00', '16:00']}, 
        'place': 'ch', 
        'extra': None,
        'enextra': None,
        'stamp': False,
    },
    {
        "id": "속풀이라면-ch",
        "main": "속풀이라면",
        "enmain": "Sokpul Ramen",
        "side": None,
        "enside": None,
        "price": 3500,
        "day": None,
        "time_category": ["breakfast"],
        "time_detail": {"breakfast": ["09:00", "10:00"]},
        "place": "ch",
        "extra": None,
        "enextra": None,
        "stamp": False,
    },
    {
        "id": '공깃밥-ch',
        "main": "공깃밥",
        "enmain": "Rice",
        "side": None,
        "enside": None,
        "price": 800,
        "day": None,
        "time_category": ["breakfast", "snack"],
        "time_detail": {"breakfast": ["09:00", "10:00"], "snack": ["15:00", "16:00"]},
        "place": "ch", 
        "extra": None,
        "enextra": None,
        "stamp": False,
    },
    {
        'id': '짜계치-ch',
        "main": "짜계치",
        "enmain": "Jja-gye-chi",
        "side": None,
        "enside": None,
        "price": 3800,
        "day": None,
        "time_category": ["snack"],
        "time_detail": {"snack": ["15:00", "16:00"]},
        "place": "ch",
        "extra": None,
        "enextra": None,
        "stamp": False,
    },
    {
        'id': '콘치즈불닭면-ch',
        "main": "콘치즈불닭면",
        "enmain": "Corn Cheese Buldak Noodles",
        "side": None,
        "enside": None,
        "price": 3800,
        "day": None,
        "time_category": ["snack"],
        "time_detail": {"snack": ["15:00", "16:00"]},
        "place": "ch",
        "extra": None,
        "enextra": None,
        "stamp": False,
    }
 ]
}
