"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

try:
    import dotenv
    dotenv.load_dotenv()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h=*wyi-pqo-i2$%15#yx(!1mruj0)5y0m^nj-jve0j*_kk#i@f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '134.185.111.151,127.0.0.1,localhost,kie.khusan.co.kr').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_browser_reload',
    'restaurants.apps.RestaurantsConfig',
    'pwa',
    # 'pages'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'restaurants.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurants.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Uses Cloudflare D1 via HTTP API.

CLOUDFLARE_ACCOUNT_ID = os.environ.get('CFACCOUNTID')
CLOUDFLARE_D1_DATABASE_ID = (
    os.environ.get('CFDATABASEID')
)
CLOUDFLARE_API_TOKEN = (
    os.environ.get('CFTOKEN')
)

DATABASES = {
    'default': {
        'ENGINE': 'restaurants.d1_backend',
        'CLOUDFLARE_ACCOUNT_ID': CLOUDFLARE_ACCOUNT_ID,
        'CLOUDFLARE_DATABASE_ID': CLOUDFLARE_D1_DATABASE_ID,
        'CLOUDFLARE_API_TOKEN': CLOUDFLARE_API_TOKEN,
    }
}

# Oracle Cloud Object Storage
ORACLE_NAMESPACE = 'ax0ym4amgnfk'
ORACLE_BUCKET = 'bucket-20260516-0145'
ORACLE_REGION = 'ap-chuncheon-1'

# Optional: sub-folder inside the bucket used as the media root
ORACLE_MEDIA_LOCATION = 'media'

# Optional: public base URL for the bucket (set if bucket is public or uses PAR)
# ORACLE_STORAGE_URL = 'https://objectstorage.ap-chuncheon-1.oraclecloud.com/n/ax0ym4amgnfk/b/bucket-20260516-0145/o/'

# Optional: OCI credentials (defaults to ~/.oci/config)
# ORACLE_CONFIG_FILE = '~/.oci/config'
# ORACLE_CONFIG_PROFILE = 'DEFAULT'

# Django media file storage backend
DEFAULT_FILE_STORAGE = 'restaurants.oracle_storage.OracleObjectStorage'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko'

LANGUAGES = [
    ('ko', 'Korean'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'restaurants' / 'static',
]

# LOGIN_URL = '/django-admin/login/'
LOGOUT_REDIRECT_URL = 'home'

# PWA Settings
PWA_APP_NAME = 'The Bob App'
PWA_APP_DESCRIPTION = "My Bob App"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/favicon.jpg',
        'sizes': '192x192',
        'type': 'image/jpg'
    },
    {
        'src': '/static/favicon.jpg',
        'sizes': '512x512',
        'type': 'image/png'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/favicon.jpg',
        'sizes': '192x192',
        'type': 'image/jpg'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
# PWA_SERVICE_WORKER_PATH = BASE_DIR / 'restaurants' / 'serviceworker.js'

# Use signed cookie-based sessions to prevent SessionInterrupted errors on Turso database due to concurrent requests (e.g. django-browser-reload pings during login session rotation).
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
