name: Django CI/CD

on:
  push:
    branches: [ "bravo" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      # - run: pip install -r requirements.txt
      # - run: python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          # host: ${{ secrets.SERVER_IP }}
          # username: ${{ secrets.SERVER_USER }}
          # key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/dir/food
            git pull origin bravo
            # pip install -r requirements.txt
            # python manage.py migrate --noinput
            pm2 restart ecosystem.config.js